#ifndef _CONFIGURATION_HPP_
#define _CONFIGURATION_HPP_

// -- SERVO POSITIONS --

#define CLAMP_OPEN_POS 40   // TODO
#define CLAMP_CLOSED_POS 6  // TODO

#define BANNER_1_DEPLOYED_POS 50  // TODO
#define BANNER_1_RETRACTED_POS 5  // TODO

#define BANNER_2_DEPLOYED_POS 50  // TODO
#define BANNER_2_RETRACTED_POS 5  // TODO

// -- STEPPERS CONFIGURATION (ELEVATORS) --

#define ELEVATOR_1_STEP_PER_REV 200 // TODO
#define ELEVATOR_2_STEP_PER_REV ELEVATOR_1_STEP_PER_REV // TODO

#define ELEVATOR_1_SPEED 50 // rev per minute // TODO
#define ELEVATOR_2_SPEED ELEVATOR_1_SPEED // rev per minute // TODO

// number of steps between states DOWN and UP - change sign to invert direction
#define ELEVATOR_1_POS_OFFSET 200 // TODO
#define ELEVATOR_2_POS_OFFSET ELEVATOR_1_POS_OFFSET // TODO

// -- PINS --

#define ELEVATOR_1_STEP_PIN 3
#define ELEVATOR_1_DIR_PIN 4

#define ELEVATOR_2_STEP_PIN 5
#define ELEVATOR_2_DIR_PIN 6

#define CLAMP_1_1_PIN 20 
#define CLAMP_1_2_PIN 21
#define CLAMP_2_1_PIN 22
#define CLAMP_2_2_PIN 23 

#define BANNER_1_PIN 9
#define BANNER_2_PIN 10

// -- OTHER CONFIG --

#define CALLBACK_INTERVAL 1000  // ms
#define BANNER_INTERVAL 1000    // ms // TODO

#endif